---
title: "Unequal_variance_ttest"
author: "Hannah Dugdale"
date: "11/14/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
sessionInfo() #R 3.4.0, nortest_1.0-4

# P2005_I&SI_F
P2005_ISI_F = c(1, 3, 4, 6, 7, 8)
P2005_ISI_M = c(2, 5)

# Test for equal variances
var.test (P2005_ISI_F,P2005_ISI_M)
# https://www.r-bloggers.com/two-sample-students-t-test-1/
# F = 1.5481, num df = 5, denom df = 1, p-value = 0.9161; P>0.05 so assume are the same variance
qf(0.95, 5,1)
# 230.1619
# the value of F computed in t.test is less than the tabulated value of F from qf so accept homogenity of variances

# Test for normality; p<0.05 deviates from normality
shapiro.test(P2005_ISI_F)
# W = 0.96579, p-value = 0.8631
shapiro.test(P2005_ISI_M)
# sample size must be between 3 and 5000
library(nortest)
ad.test(P2005_ISI_M)
cvm.test(P2005_ISI_M)
# sample size must be greater than 7
sf.test(P2005_ISI_M)
# sample size must be between 5 and 5000
pearson.test(P2005_ISI_M)
# P = 1, p-value < 2.2e-16
P2005_ISI_Sex = c(0, 0, 0, 0, 0, 0, 0, 1, 1)
P2005_ISI_Rank = c(1, 3, 4, 6, 7, 8, 9, 2, 5)
wilcox.test(P2005_ISI_Rank~P2005_ISI_Sex)
# W = 10, p-value = 0.5

#t.test(P2005_ISI_F,P2005_ISI_M, var.equal=FALSE, paired=FALSE)
# t = -0.87831, df = 6.1189, p-value = 0.4129
# t.test(P2005_ISI_F,P2005_ISI_M, var.equal=TRUE, paired=FALSE)
# t = -0.75337, df = 7, p-value = 0.4758

###################################
#
#  Steepness DS rank sex test
#
###################################

SH1995_DS_F = c(2, 6, 10, 14)
SH1995_DS_M = c(1, 3, 4, 5, 7, 8, 9, 11, 12, 13)
var.test (SH1995_DS_F,SH1995_DS_M)
# ok: F = 1.6427, num df = 3, denom df = 9, p-value = 0.4953
qf(0.95, 3,9)
# ok: 3.862548
shapiro.test(SH1995_DS_F)
# ok: W = 0.99291, p-value = 0.9719
shapiro.test(SH1995_DS_M)
# ok: W = 0.96552, p-value = 0.8465
t.test(SH1995_DS_F,SH1995_DS_M, var.equal=TRUE, paired=FALSE)
# No effect: t = 0.27259, df = 12, p-value = 0.7898

P1995_DS_F = c(1, 2, 3, 4, 8, 9, 10)
P1995_DS_M = c(5, 6, 7, 11)
var.test (P1995_DS_F,P1995_DS_M)
# ok: F = 1.9139, num df = 6, denom df = 3, p-value = 0.635
qf(0.95, 6, 3)
# ok: 8.940645
shapiro.test(P1995_DS_F)
# ok: W = 0.89571, p-value = 0.3058
shapiro.test(P1995_DS_M)
# ok: W = 0.88691, p-value = 0.369
t.test(P1995_DS_F,P1995_DS_M, var.equal=TRUE, paired=FALSE)
# No effect: t = -0.93934, df = 9, p-value = 0.3721

PO2004_DS_F = c(1, 2, 4, 5)
PO2004_DS_M = c(3, 6, 7)
var.test (PO2004_DS_F,PO2004_DS_M)
# ok: F = 0.76923, num df = 3, denom df = 2, p-value = 0.7842
qf(0.95, 3, 2)
# ok: 19.16429
shapiro.test(PO2004_DS_F)
# ok: W = 0.94971, p-value = 0.7143
shapiro.test(PO2004_DS_M)
# ok: W = 0.92308, p-value = 0.4633
t.test(PO2004_DS_F,PO2004_DS_M, var.equal=TRUE, paired=FALSE)
# No effect: t = -0.35806, df = 5, p-value = 0.7349


P2005_DS_F = c(1, 2, 3, 5, 6, 7, 9)
P2005_DS_M = c(4, 8)
var.test (P2005_DS_F,P2005_DS_M)
# ok: F = 1.0298, num df = 6, denom df = 1, p-value = 0.7249
qf(0.95, 6,1)
# ok: 233.986
shapiro.test(P2005_DS_F)
# ok: W = 0.96973, p-value = 0.8965
shapiro.test(P2005_DS_M)
# sample size must be between 3 and 5000
pearson.test(P2005_DS_M)
# ok: P = 1, p-value < 2.2e-16
# t.test(P2005_DS_F,P2005_DS_M, var.equal=TRUE, paired=FALSE)
# No effect: t = -1.7321, df = 7, p-value = 0.1269
P2005_DS_Sex = c(0, 0, 0, 0, 0, 0, 0, 1, 1)
P2005_DS_Rank = c(1, 2, 3, 5, 6, 7, 9, 4, 8)
wilcox.test(P2005_DS_Rank~P2005_DS_Sex)
# No effect: W = 5, p-value = 0.6667

# Don't test PO2005 as no steep hierarchy
PO2005_DS_F = c(1, 2, 5)
PO2005_DS_M = c(3, 4)
var.test (PO2005_DS_F,PO2005_DS_M)
# ok: F = 8.6667, num df = 2, denom df = 1, p-value = 0.4671
qf(0.95, 2,1)
# ok: 199.5
shapiro.test(PO2005_DS_F)
# ok: W = 0.92308, p-value = 0.4633
shapiro.test(PO2005_DS_M)
# sample size must be between 3 and 5000 
t.test(PO2005_DS_F,PO2005_DS_M, var.equal=TRUE, paired=FALSE)
# No effect: t = -0.52223, df = 3, p-value = 0.6376


```

